services:
  postgres:
    image: postgres:17.5
    container_name: wonzzang_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
